### ISSUE TITLE
Badge Service!

### ISSUE THREAD

**Issue by Bartvds** [DefinitelyTyped/badges#3]
There is also this: http://shields.io/

It creates the common badges in SVG (via the URL), but does some custom services too.

Some quick example:

![DefinitelyTyped](http://img.shields.io/badge/TS-DefinitelyTyped-blue.svg)

![DefinitelyTyped](http://img.shields.io/badge/DT-DefinitelyTyped-blue.svg)

![DefinitelyTyped](http://img.shields.io/badge/DefinitelyTyped-TS-blue.svg)

![DefinitelyTyped](http://img.shields.io/badge/Definitely-Typed-blue.svg)

Has a few default colors but we can probably hustle a custom bright TypeScript Blue.

The nice thing about these is how they fit with the Travis badges so people might be more amendable to putting them on their project. My OCD cannot handle it when they look off or have weird sizes, like the horrible AppVeyor badge :wink:
## 

The basic badges are URL configurable, very easy to experiment: 

![DefinitelyTyped](http://img.shields.io/badge/foo-bar-green.svg)

```
![DefinitelyTyped](http://img.shields.io/badge/foo-bar-green.svg)
```

**Comment by Diullei** [comment]
Very cool!!!

I enjoyed the first one.

**Comment by staxmanade** [comment]
:+1: for the first one.

**Comment by borisyankov** [comment]
Like the first one, but a lowercase 'ts' or '.d.ts' might be a good option.

**Comment by Bartvds** [comment]
Lower-case ts to complete the set:

![DefinitelyTyped](http://img.shields.io/badge/ts-DefinitelyTyped-blue.svg)

![DefinitelyTyped](http://img.shields.io/badge/DefinitelyTyped-ts-blue.svg)

But as we're all about `.d.ts` that fits nicely:

![DefinitelyTyped](http://img.shields.io/badge/.d.ts-DefinitelyTyped-blue.svg)

![DefinitelyTyped](http://img.shields.io/badge/DefinitelyTyped-.d.ts-blue.svg)

**Comment by staxmanade** [comment]
I like the last one (but it's a close call)

**Comment by johnnyreilly** [comment]
I like .d.ts too - it says what DT is about nicely

**Comment by basarat** [comment]
I like the last one as well :+1:

**Comment by Bartvds** [comment]
Cool. So we go for 

![DefinitelyTyped](http://img.shields.io/badge/DefinitelyTyped-.d.ts-blue.svg)

And a flat one:

![DefinitelyTyped](http://img.shields.io/badge/DefinitelyTyped-.d.ts-blue.svg?style=flat)

Next time I edit the site I'll add a page with some copy-pastable markdown etc. 

I'll also add the file under the definitelytyped.org domain so we can remote-update it easily.

Suggestions for an title/alt-text are welcome :)

**Comment by Bartvds** [comment]
Cool, these is now live and linked on the website.

Labelled 'experimental' for now but at least we have something to work with.

I copied the SVG's to http://definitelytyped.org so we can update them if need be.

See http://definitelytyped.org/pages/badges.html

**Comment by Diullei** [comment]
Great job Bart!

Just an idea, I think the link could point directly to the typing instead pointin to definitelytyped.org. 

Something like this:

```
[![TypeScript definitions on DefinitelyTyped](//definitelytyped.org/badges/standard.svg)](https://github.com/borisyankov/DefinitelyTyped/tree/master/qunit)
```

Another idea is to pointing to a specific .d.ts page on definitelytyped.org with some info about the .d.ts:

Example of a Badge to Qunit .d.ts

```
[![TypeScript definitions on DefinitelyTyped](//definitelytyped.org/badges/standard.svg)](definitelytyped.org/typing-qunit.html)
```

And the `/typing-qunit.html` page could be automatically generated with some data like TSD, Nuget and Github statistics .

What do you think?

**Comment by Bartvds** [comment]
Oh yes, I really like the second one. The old TSD site had a popup like that.

We'd need a widget to generate a custom link to a info page about the typing. 

I created a ticket on the site: https://github.com/DefinitelyTyped/definitelytyped.github.io/issues/12

Ideally it has a filter selector thing that suggest from a index JSON but I can make a start with a simpler one.

**Comment by Diullei** [comment]
Nice!
